# HW 7 - Libraries + Modules
ULAB - Physics and Astronomy Division \
Due **Wednesday, November 6th, 2024 at 11:59pm** on Gradescope

--------------------------------------------------------------

## Module vs. Package vs. Library
### Module
A **module** is a single file containing Python code (typically ending in a `.py` extension) that contains functions and variables. 
- They can be imported into other Python files or notebooks
- You use modules to organize code into smaller, reuseable parts
- Ex: `even_sum.py` that we created during lecture.

*You will create your OWN module for this homework and use that we made during class.*

### Package
A **package** is a group of modules, organized like a directory. 
- A package requires a special `__init__.py` file to tell Python that the ENTIRE directory is something you would like to import.
- Packages can contain sub-pacakges
- Ex: `BAGLE_Microlensing` is an example of a package (if you are in Dex's group, this should be familar to you). Or you could think of `paarti` if you are in Brianna's group.

*You will NOT be working with a package for this homework.*

### Library
A **library** is a much broader term that also refers to a collection of modules (like a package) but a library can also contain mulitple packages. 
- Libraries serve a much wider range of functionality for
- Programmers use packages to have ready-to-go tools that can be used for data manipulation, web development, machine learning or simulations.
- Ex: `numpy` is a very common library. Later in this course we will also be working some of the following libraries `matplotlib`, `scipy`, and `astropy`, `pandas`, etc

*You WILL be working with the extensive numpy library for this homework!*

--------------------------------------------------------------

# 1 NumPy
**NumPy** (aka Numerical Python) is a library that was designed for caring out computations in Python. 

We did not have a ton of time to work through examples during class, so I will ask that you check out this website for more information: https://numpy.org/doc/ 

Before we can work through any problems, you need to call the following in your notebook:

In [203]:
import numpy as np

## 1.1 Lists vs. Arrays
*When I first started working with NumPy I didn't understand what was so special about arrays. This homework problem should help illustrate the difference. Make sure to follow each step and follow good coding practices.*

1) Make a list called `my_list` and make an array called `my_arr` with the same values. There is an example below, but don't copy mine! Ex:
```
my_list = [11, 12, 13, 14, 15]
my_arr = np.array([11, 12, 13, 14, 15])
```
*Notice that to use the `numpy` package we had to call its short cut `np` and then call upon its funciton `.array()`. This is similar to working with a built-in python function like `.append()`.*

In [206]:
# Your code here
my_list = [77, 88, 99, 110, 121]
my_arr = np.array([77, 88, 99, 110, 121])

2) Multiply `my_list` by 4 and multiply `my_arr` by 4. Print the results. Describe what happens in a comment.

In [209]:
# Your code here
x = my_list*4
g = my_arr* 4

print(x, g)

#Multiplying the list by 4 reiterated the list 4 times while multiplying an array by 4 multiplied each number 4 times.

[77, 88, 99, 110, 121, 77, 88, 99, 110, 121, 77, 88, 99, 110, 121, 77, 88, 99, 110, 121] [308 352 396 440 484]


3) Add `my_list` with `my_list`. Add `my_arr` with `my_arr`. Add `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [212]:
# Your code here
x = my_arr + my_list
print(x)

#This adds the numbers of the same index.

[154 176 198 220 242]


4) Subtract `my_list` with `my_list`. Subtract `my_arr` with `my_arr`. Subtract `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [215]:
# Your code here
y = my_arr - my_arr
print(y)

z = my_list - my_arr
print(z)

x = my_list - my_list
print(x)

#It would not allow me to subract two lists from one another but it allowed me to subract an array from one another and an array with a list, which just subracted the indicies.

[0 0 0 0 0]
[0 0 0 0 0]


TypeError: unsupported operand type(s) for -: 'list' and 'list'

5) Multiply `my_list` with `my_list`. Multply `my_arr` with `my_arr`. Multiply `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [218]:
# Your code here

y = my_arr * my_arr
print(y)
z = my_arr * my_list
print(z)
x = my_list * my_list


#could not multiply two lists together, however could multiply a list and an array as well as an array with an array - which multiplies the indices together.


[ 5929  7744  9801 12100 14641]
[ 5929  7744  9801 12100 14641]


TypeError: can't multiply sequence by non-int of type 'list'

7) Divide `my_list` with `my_list`. Divide `my_arr` with `my_arr`. Divide `my_list` with `my_arr`. Print the results. Describe what happens in a comment.

In [221]:
# Your code here
y = my_arr / my_arr
print(y)
z = my_arr / my_list
print(z)
x = my_list / my_list


#could not divide two lists with one another, however could divide a list and an array as well as an array with an array - which divided the indices together.


[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]


TypeError: unsupported operand type(s) for /: 'list' and 'list'

8) After working through this problem, in at least two sentences, describe the difference between a list and an array.

In [224]:
# Your code here
#An array can be used for computation much easier than a list can. A list holds pretty firm while an array can be easily manipulated and used to computer with numerical functions.

## 1.2 Nested List and Multi-Dimensional Arrays
A **nested list** is when you have a list as an element for a list. Example:
```
nested_list = [[1, 2, 3], [4, 5, 6]]
```

A **multi-dimensional array** is essentially a nested list, but it contains the properties of a matrix. Example:
```
multi_d_array = np.array([[1, 2, 3], [4, 5, 6]])
```

Go to this website for more information on NumPy: https://www.w3schools.com/python/numpy/default.asp

Write a **function** that takes in a two-dimensional array. Example:

```
arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
```

and then returns the second value in each row. Example:

```
[4, 10, 16]
```

In [227]:
import numpy as np

def get_second_value(array):
    return array[:, 1]


arr3 = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
get_second_value(arr3)


array([ 4, 10, 16])

In 2-3 sentences, describe what section of the website helped you write your function. 

In [230]:
# Your comment here
#The numpy slicing section helped me write this function. It showed me I can slice a list to produce a specific section or sections of it

How would you take a nested list and return the second value in each row? Explain in 2-3 sentences and show an example.

## 1.3 Up to You!
With the website I just gave you: https://www.w3schools.com/python/numpy/default.asp

I recommend working through the examples they provide (you don't have to do all of them, but a few would be good). It will help you build an intuition for numpy. It won't take very long, there are only a couple of examples per section.

Write you own **function** that follows the theme of one of the sections (i.e. array reshaping, array filter, random intro, etc). For example, if you are curious about the section "**NumPy Creating Arrays**" you could write a function that creates a multi-dimensional array.

```

>>> def make_multi_dimensional_array(one_d_array, dimensions):
...     # Creates a multi-dimensional array
...     # Your code here
...     return # Your code here

>>> my_one_d_array = [2, 4, 6, 8]
>>> my_dimension = 10
>>> ten_d_array = make_multi_dimensional_array(my_one_d_array, my_dimension)
>>> print(ten_d_array)
[[[[[[[[[[2 4 6 8]]]]]]]]]]

```

Your function should be more detailed than the example I gave you. Include at least one of the following: 
- a conditional statement
- an assignment operator
- a loop (`for` or `while`)
- `if`, `elif`, `else`, statement

In [234]:
def sorting_an_array(arr, ascending=True):
    #function that sorts an array in ascending or descending order
    if ascending:
        return sorted(arr)  # Sort in ascending order
    else:
        return sorted(arr, reverse=True)  # Sort in descending order

arr = [888, 4, 2, 78, 98]

#ascending order
print(sorting_an_array(arr, ascending=True))

#descending order
print(sorting_an_array(arr, ascending=False))

[2, 4, 78, 98, 888]
[888, 98, 78, 4, 2]


In the section you took inspiration from, show all of the examples below. Follow good coding practices and give at least two test cases for each example. Don't forget comments! \
\
*For my example, I took inspiration from **NumPy Creating Arrays** so I would show following examples with DIFFERENT test cases: Create a NumPy ndarray Object, Dimensions in Arrays ,0-D Arrays, 1-D Arrays, 2-D Arrays, 3-D Arrays, Check Number of Dimensions, Higher Dimensional Arrays.*

In [237]:
# Your code here


#Example1 -sorting an array in ascending order

arr = np.array([3, 2, 0, 1])
arr2 = np.array([8, 2, 1, 9])

print(np.sort(arr))
print(np.sort(arr2))

#Example2 -alphabetical sorting

arr = np.array(['banana', 'cherry', 'apple'])
arr2 = np.array(['zuchinni', 'tater tots', 'treeleaf'])

print(np.sort(arr))
print(np.sort(arr2))


#Example 3 - boolean
import numpy as np

arr = np.array([True, False, True])
arr2 = np.array([False, True, False])

print(np.sort(arr))
print(np.sort(arr2))

#Example 4 -sorting a 2d array
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])
arr2 = np.array([[7,2,9], [1,9,0]])

print(np.sort(arr))
print(np.sort(arr2))

[0 1 2 3]
[1 2 8 9]
['apple' 'banana' 'cherry']
['tater tots' 'treeleaf' 'zuchinni']
[False  True  True]
[False False  True]
[[2 3 4]
 [0 1 5]]
[[2 7 9]
 [0 1 9]]


In 2-3 sentences, describe how your function took inspiration from a section.\
\
*For my example, `make_multi_dimensional_array`, I would talk about the **NumPy Creating Arrays** section and how I took inspiration from the example **Higher Dimensional Arrays**.*

# Your comment here
I took inspiration from the NumPy Sorting Arrays section, specifically the boolean example. While I didn't sort due to boolean, I used booleans in my function to specify how I wanted the array to be sorted. Also, I was inspired by how the numbers were sorted in ascending order to figure out how to sort them in descending order.

# 2 Brianna's Module
During lecture we created and worked with a module called `even_sum.py`. Import that module here. 

In [242]:
# Your code here
import even_sum

Now that you have imported the module. Call the module and the first function with your own list of numbers. 

In [245]:
# Your code here
list1 = [2, 3, 4, 5, 6, 7, 8, 9, 10]
print(even_sum.sum_even_numbers(list1))

30


I have provided you a separate module called `example.py`. Import that module here.

In [248]:
# Your code here
import example

With the following variables, use my module to show which of the rocket's escape!

In [251]:
rocket_velocities = np.array([
    [1000, 5000, 8000, 12000],  # Rocket 1's velocity at different times
    [2000, 6000, 9000, 10000],  # Rocket 2
    [3000, 3100, 3200, 3300]    # Rocket 3
])

mass_of_planet = 5.972e24 # kilograms
radius_of_planet = 6.371e6 # meters

In [253]:
# Your code here
escape_velocity = example.escape_velocity(mass_of_planet, radius_of_planet)
print("Escape velocity:   ", escape_velocity)

orbital_velocity = example.orbital_velocity(mass_of_planet, radius_of_planet)
print("Orbital Velocity:   ", orbital_velocity)

rocket_launch = example.rocket_launch(rocket_velocities, mass_of_planet, radius_of_planet)




Escape velocity:    11185.97789184991
Orbital Velocity:    7909.680821529872


In 2-3 sentences describe how this code follows "good coding practices" and where there is room for improvement.

# Your comments here
This code follows good coding practices because each function's use is described as well as the input and outputs for each. What can be improved is including at the end of the module the ability to print which rocket successfully leaves the orbit. What I mean by this is adding a statement that gives the module the ability to just print the specific rocket(s) (i.e. Rocket 1) that are able to leave orbit. 

# 3 Your Turn!
Now its your turn to make a module! Choose a topic from a class (could be physics, computer science, nuclear engineering, biology, astronomy, math, or an topic that interests you!) and build a module around it! Look at my module called `example.py` and base your structure around it. Your module NEEDS to include the following.

Overall:
1) Your module needs to use at least one NumPy function: https://numpy.org/devdocs/reference/routines.math.html
2) Your module needs to contain a multi-dimensional array: https://numpy.org/devdocs/reference/arrays.ndarray.html 
3) Your module needs **at least** three functions that follow good coding practices.
4) Inside your function, include comments. Don't forget to describe what the function is doing and what the inputs and outputs are.
5) Your module needs either a `for` loop or `while` loop.
6) Your module needs an `if`, `elif`, and `else` statement.
7) Your module needs at least two assignment variables (`+=`, `*=`, etc).
8) Creativity. *If it looks like you plugged this whole thing into ChatGPT, I will take off points. You can use ChatGPT to help you code, but you can't use it to just do your homework for you. That's no fun :(*

In 2-3 sentences, describe the topic of your module and its capabilities. 

# Your comment here
The topic of my module is DNA transcription and translation. The functions generate a slightly random dna sequence, transcribe it into RNA, then translate it into a protein sequence.

In 2-3 sentences, answer the following. What was the most challenging part of building this module? What did you learn in the process that you can apply to future coding assignments?


In [260]:
# Your comment here
#The most challenging part of building this module was trying to figure out how to connect the three functions. Creating them was very difficult too, but splitting up my idea into three functions and implementing them so they worked together was difficult. I learned a lot about breaking up my goal step by step and working through each function as a part of a whole.

Once your module is complete, import it here.

In [263]:
# Your code here
import dna_to_protein

Call each of your functions in the cell below. Make sure to show the outputs! 

In [266]:
# Your code here

length = 20

#Generate
DNA_sequence = dna_to_protein.generate_sequence(length)
print("DNA Sequence:   ", DNA_sequence)

#Transcribe
rna_sequence = dna_to_protein.transcribe_sequence(DNA_sequence)
print("RNA Sequence:   ", rna_sequence)

#translation
protein_sequence = dna_to_protein.translate_sequence(rna_sequence)
print("Protein Sequence:", protein_sequence)

DNA Sequence:    ACGTTGCACATGGTACACGT
RNA Sequence:    ACGUUGCACAUGGUACACGU
Protein Sequence: TLHMVHX


# 4 Proper Submission
To recieve full credit for this assignment make sure you do the following:

1) Copy this homework assignment from the `ulab_2024` repository into **YOUR** local `homework7` branch. It will contain this notebook and an additional file called `example.py`. 
   
2) Follow the tasks. Make sure to run all the cells so that **all** output is visible. You will get points taken off if your ouputs are not shown!

3) Add/commit/push this notebook and **ANY** modules (so you should have `example.py` and your module) used in this homework assignment to your remote `homework7` branch. Make sure to have NOTHING else in your branch (i.e. no previous homeworks or lecture notes).

4) Do the following:
- Take a screenshot of moving **into or out** of your `homework7` brach, call it `hw7_branch`.
- Take a screenshot of calling `ls` in your `homework7` branch, it should only contain items relevent to homework 7, call it `hw7_ls`.
- Take a screenshot of adding this assignment to your local `homework7` branch, call it `hw7_add`.
- Take a screenshot of committing this assignment to your local `homework7` branch, call it `hw7_commit`.
- Take a screenshot of pushing this assignment to your remote `homework7` branch, call it `hw7_push`. 

6) Include these screenshots in your `homework7` branch. Upload your `homework7` branch to Gradescope!